server.port=${PORT:10000}
spring.datasource.url=${MINHA_CONEXAO_URL}
spring.datasource.username=${MINHA_CONEXAO_USER}
spring.datasource.password=${MINHA_CONEXAO_PASS}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false