spring.application.name=CadastroAtletas

spring.datasource.url=jdbc:postgresql://localhost:5432/ct_ferroviario
spring.datasource.username=postgres
spring.datasource.password=21049511
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true